### ISSUE TITLE
request to integrate with express

### ISSUE THREAD

**Issue by conanchen** [jed/authom#10]
authom source code looks very clean and easy to understand, but i got a problem to integreate with express,specifically i want to save the authenticated user information into express session.

  app.use(express.session({
      secret: 'xxx',
      store: memoryStore,
    }));

i want to set session in authom.on("auth", function(req, res, data) {
        req.session.auth=true;
        req.session.username= data.user.Name;
})

so that i can check whether user is authenticated or not in express

app.get("secpath",function(){
  if(!req.session.auth) redirect("/auth/github");  //<-- but i can not get req.session.auth value as true, the session lost!
})

can someone show how to write a authom middleware for express or other solution?

**Comment by jed** [comment]
i built authom to be framework-agnostic. i'd welcome a wiki page about how to integrate with express, but if you're looking for better express integration now, maybe @bnoguchi's [everyauth](https://github.com/bnoguchi/everyauth) might work better for you?

**Comment by zenlor** [comment]
It just works(tm) in Express (and therefore Connect)

``` js
authom.createServer(...);

app.get("/auth/:service", authom.app)

authom.on("auth", function(req, res, data) {
  req.session.user = data;
  res.redirect('/dashboard');
});

var filter = function (req, res, next) {
      if (!! req.session.user)
        next();
      else
        res.redirect('/');
    }

app.get('/dashboard', filter, function (req, res) {
  res.render("dashboard", {
    title: "dashboard"
  })
});
```

`req` and `res` are given to authom via express/connect, so you can treat the two handlers as a simple route.

ps. thank you Jed for writing this clean library (everyauth is a mess from my point of view).

**Comment by jed** [comment]
thanks, @aliem! i completely forgot about this issue.
