### ISSUE TITLE
Services files aren't getting downloaded

### ISSUE THREAD

**Issue by mrw4n** [jed/authom#12]
meetup.js and twitter.js service files are not getting downloaded using:

npm install authom

**Comment by mrw4n** [comment]
Note:

when downloading the twitter.js file manually it still cant recognize it, and triggers the following error:

No such service: /var/www/egaz/node_modules/authom/lib/services/twitter

**Comment by jed** [comment]
the latest in the repo is on npm now, can you try installing again?

**Comment by mrw4n** [comment]
thanks a lot, working good now.
