### ISSUE TITLE
Error in express.js example

### ISSUE THREAD

**Issue by mrw4n** [jed/authom#13]
When twitter emits an error like the following:

{ statusCode: 401,
  data: '<?xml version="1.0" encoding="UTF-8"?>\n<hash>\n  <error>Invalid / expired Token</error>\n  <request>/oauth/access_token</request>\n</hash>\n' }

it triggers the following error:

Uncaught exception: TypeError: Object #<ServerResponse> has no method 'error' 

cause of this:

authom.on('error', function(req, res, data) {
    res.error("An error occurred: " + JSON.stringify(data))
});

cause the res object doesnt have the method "error".

**Comment by recipher** [comment]
This will be fixed by pull request #77.
