### ISSUE TITLE
npm version is not updated with refresh_token implementation :(

### ISSUE THREAD

**Issue by gkrcode** [jed/authom#37]
Hi,

npm version seem to be not updated with refresh_token implementation.

Thanks

**Comment by jed** [comment]
ah, sorry about that. just published, so give it another try, okay?

**Comment by gkrcode** [comment]
Hi, npm version has updated now but Google authentication has refresh_token as undefined :(

**Comment by jed** [comment]
that's no good. @ryedin, would you mind taking a look at your implementation?
