### ISSUE TITLE
Work on node 0.10.0

### ISSUE THREAD

**Issue by cartuchogl** [jed/authom#39]
Hello,

Today, I try to run my app that use authom on node 0.10.0. With OAuth2 Services it fails. I review API changes on new version of node at this page https://github.com/joyent/node/wiki/Api-changes-between-v0.8-and-v0.10 , and I change the inheritance method used by the recomend on this page. I need to add more change for pass my custom tests. I try with twitter, facebook, foursquare, instagram and github with sucess, but not extensive. The changes are in https://github.com/cartuchogl/authom/commit/5d4058004289b25711ed81d51fefe8ebe809dc5c

Tomorrow I try to do more tests.

**Comment by jed** [comment]
great, thanks for kicking this off, @cartuchogl. would love a pull request once you have a better idea of what needs fixing.

**Comment by cartuchogl** [comment]
I extract from my tests stack the part that refer authom. Only support a few networks. I will try to add more networks. The work is in that branch https://github.com/cartuchogl/authom/tree/node_0.10

**Comment by georgesnelling** [comment]
Hey Jed, 
I'm not sure if this is related to deedbubs changes or not, but running the authom@0.4.12 sample server against node 0.10.4, the following samples work fine:

twitter
linked-in

However, the following all fail with some version of this:  
An error occurred: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","service":"github"}

github
google
facebook
foursquare

Didn't try the others as I don't have accounts set up.  If you cannot repro from your side let me know and I'll keep digging.

**Comment by jed** [comment]
the problem is that a node internal https refactor prevented inherited properties of the request from being picked up. so now copying instead of inheriting.

**Comment by georgesnelling** [comment]
verified fixed.  bump version?

**Comment by jed** [comment]
already bumped in npm, will push to github tomorrow.

jed

**Comment by georgesnelling** [comment]
Ah I see. Thanks for your work, peace out.
