### ISSUE TITLE
Possible compatibility break between 0.4.7 and 0.4.8

### ISSUE THREAD

**Issue by ovaillancourt** [jed/authom#41]
Hi there,

We just had a big issue after installing 0.4.8 - all of our facebook authentications stopped working until we reverted to 0.4.7. 

I'll investigate further and follow up on this ticket. - Wanted to drop a word on this if anyone experienced similar issues.

( I know I'm 3 months late since 0.4.8 - seems to be a weird edge case.)

**Comment by ovaillancourt** [comment]
Ok - I've narrowed the issue down to this specific commit:

ba27e78fc1e2a6997edab4675866c1d63e62bd98

Passing the refresh-token "as-is" means it gets stringified to "undefined" when not set and sent to facebook as such.

I'll submit a patch in a subsequent pull request.

**Comment by jed** [comment]
@ovaillancourt, thanks for the heads up. standing for the patch...

**Comment by ovaillancourt** [comment]
Yes - actually I'm thinking that the issue might be a bit deeper than just this commit and might be caused by a small  peripheral change on facebook's end or a bug in oauth2 elsewhere.

If I'm not mistaken, that line in the above commit only affects what is being returned to the lib user's in the "auth" callback right? So I'm not clear on how it's affecting what facebook hands me back.

**Comment by jed** [comment]
yeah, this adds a field in the returned data, so i'm not sure how this
would cause auth failure. i'd imagine the issue might be elsewhere, perhaps
in another commit?

On Tuesday, March 26, 2013, Olivier Vaillancourt wrote:

> Yes - actually I'm thinking that the issue might be a bit deeper than just
> this commit and might be caused by a small peripheral change on facebook's
> end or a bug in oauth2 elsewhere.
> 
> If I'm not mistaken, that line in the above commit only affects what is
> being returned to the lib user's in the "auth" callback right? So I'm not
> clear on how it's affecting what facebook hands me back.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jed/authom/issues/41#issuecomment-15469991
> .

## 

heads up: my email address is now where@jed.is, so plan accordingly.

**Comment by ovaillancourt** [comment]
Yeah I'll dig further - I know that if I delete the line completely the issue is gone. 

We're wrapping authom on our end - could be a weird interaction with the wrapper, I'll continue investigating.

**Comment by ovaillancourt** [comment]
Ok so I confirm - I completely mis-diagnosed the whole thing.

And now I'm confused - there seems to be a v0.4.9 on npm for authom, but the current package.json on master says 0.4.8.

The break seems to have happenned between 0.4.8 and that ghost 0.4.9 version.

**Comment by ovaillancourt** [comment]
Ok! There we go with the real issue:

https://github.com/jed/authom/commit/6fd282eb4c83b4eeff71d7c19a4ff56f5324e7e4#L1R44

See the in-code comment in the above url.
