### ISSUE TITLE
How do I set the OAuth redirect URI to be https?

### ISSUE THREAD

**Issue by thomaswhite** [jed/authom#53]
Great work! I like authom a lot and it is a breath of fresh air after working with passport.js.

OAuth redirect URI is expected to be HTTPS if the URL is not localhost. 
Could you please provide an example how to set autom to listen to HTTPS redirects.

**Comment by jed** [comment]
@thomaswhite, i'm not sure i understand what you mean...

if you'd like to use an HTTPS server, you'd use the code from example but `require("https")` instead of `require("http")`.

does that answer your question?

**Comment by thomaswhite** [comment]
What I am interested is In how in the context of an Express application that runs on http to add an authom module that listens on https. 
BTW, what is the callback  URL we register in the in the service provider? Is it https://mywebseite.com/auth ?

**Comment by jed** [comment]
@thomaswhite, this is covered in the README: https://github.com/jed/authom#authomcreateserveroptions-functionreq-res
