### ISSUE TITLE
Need way to pass rejectUnauthorized to authom when using node v0.10.23

### ISSUE THREAD

**Issue by DavidZey** [jed/authom#54]
With the new security changes with the node https module, self-signed certs are rejected by default. There is an override that can be set called rejectUnauthorized. My thought is to add the override into authom, but I may also not be aware of a workaround. Is this a known issue with workaround or something that should be added to authom? Thanks.

**Comment by jed** [comment]
@DavidZey, i'm not too familiar with the issue, to be honest (i do most termination in front of node). would definitely welcome a PR if you figure it out.

**Comment by jed** [comment]
fixed by #56.
