### ISSUE TITLE
Multiple services not working

### ISSUE THREAD

**Issue by danielepolencic** [jed/authom#61]
Hello,

I noticed that it's not possible to use more than one service with the library, despite using the `name` field. Example:

``` javascript
var app = require("express").createServer()
  , authom = require("authom")

var one = authom.createServer({
  name: "facebook-one",
  service: "facebook",
  id: "1",
  secret: "mylittlesecret",
  scope: [],
  fields: ["name", "picture"]
})

var two = authom.createServer({
  name: "facebook-two",
  service: "facebook",
  id: "2",
  secret: "mylittlesecret",
  scope: [],
  fields: ["name", "picture"]
})

console.log('one: ', one.code)
// { ... query: { client_id: '2', scope: '' } } <- I was expecting client_id: '1'
console.log('two: ', two.code)
// { ... query: { client_id: '2', scope: '' } }

app.get("/auth/:service", authom.app)
app.listen(8000)
```

In other words, the last service overwrite all the other services. I dug into the code and I figured out that you store instance variables on the prototype. Hence when one of those variables change, all the instances see the new change. Example:

``` javascript
function myClass(){}
myClass.prototype = {
    settings: {name: 'random'}
};

m1 = new myClass();
m2 = new myClass();

m1.settings.name // 'random'
m2.settings.name // 'random'
m1.settings.name = 'Daniele'
m1.settings.name // 'Daniele'
m2.settings.name // 'Daniele' <- You might have expected 'random'
```

Fixing the issue is very straightforward and requires to move the properties on the prototype within the constructor.
I was about to propose a pull request when I realised that Facebook wasn't the only service suffering from this problem. At this point I think I'm not sure I can help you further. If you're happy for me to move all the properties on the prototype within the constructor, just let me know and I'll send you a pull request.

Thanks
Daniele

**Comment by jed** [comment]
@danielepolencic, i've never tried multiple instances of the same service (never had that need), but this is clearly not good! feel free to pull things into the instance if you'd like and send a PR!
