### ISSUE TITLE
Simple password/username support?

### ISSUE THREAD

**Issue by kokujin** [jed/authom#66]
I would like to allow users to create new accounts or use existing ones like Facebook for my app. Is this possible? Thanks

**Comment by nevf** [comment]
I'd like to see simple Username + Password support as well.

**Comment by auser** [comment]
Me too.

**Comment by kokujin** [comment]
@jed Or do you have an example somewhere? Thanks

**Comment by jed** [comment]
to be honest, this really isn't what i had in mind with authom, but i'll definitely entertain PRs if they're not too obtrusive with existing uses.
