### ISSUE TITLE
Linkedin

### ISSUE THREAD

**Issue by Siron** [jed/authom#75]
Hello,

I tried playing around with Authom and Linkedin, below is a snippet of the setup

  authom.createServer({
    service: 'linkedin',
........
    scope: ['r_basicprofile', 'r_emailaddress'],
    fields: ['email-address', 'first-name', 'last-name', 'picture-url']
  });

I get all the fields requested apart from email-address. Is it possible that email-address is not bound on return?

It's unlikely to be the Linkedin app because r_emailaddress is checked in.

Thanks

**Comment by jed** [comment]
@Siron,

the linkedin implementation is [here](https://github.com/jed/authom/blob/master/lib/services/linkedin.js). your best bet may be to insert some debug logging to see that everything is being picked up as you expect.

**Comment by Siron** [comment]
Thanks for the heads up - I got side tracked doing other things. I'll will close it for now. I have an active fork so I will fix anything that impacts my project and do a pull-request if needed. 

Thanks again
