### ISSUE TITLE
Why twitter service is missing

### ISSUE THREAD

**Issue by cayasso** [jed/authom#9]
Is there a particular reason why Twitter is missing, I just realized that it wasnt on your list and wanted to know if there is a special reason or perhaps no one is asking for it :(

Thank you and great job, I love authom and might be using in couple projects soon.

JB

**Comment by jed** [comment]
yeah, [twitter is still using oauth 1.0a](https://dev.twitter.com/docs/auth/oauth), which is much more cumbersome to implement:

![oauth 1.0a clusterfuck](https://dev.twitter.com/sites/default/files/images_documentation/oauth_diagram.png)

twitter would definitely be next, so if anyone wants to tackle implementing it in a dependency-free way, i'd be ecstatic.

**Comment by cayasso** [comment]
Ok got ya thanks for the clear information you provided!

**Comment by jed** [comment]
by the way, i just added twitter support, so go crazy.

**Comment by cayasso** [comment]
Awesome @jed, I will go crazy now :-) thank you man!
